

export enum  ActionTypes {
	GET_PRODUCTS = "GET_PRODUCTS",
	ADD_TO_CART = "ADD_TO_CART",
	DELETE_FROM_CART="DELETE_FROM_CART",
	UPDATE_CART_QUANTITY="UPDATE_CART_QUANTITY",
	UPDATE_CONTAINER="UPDATE_CONTAINER"
}
